### ISSUE TITLE
import {ChatCompletionRequestMessage, Configuration, OpenAIApi} from "openai";

### ISSUE THREAD

**Issue by MaelHan** [shin202/ChatGPT-Discord-Bot#69]
Hello, i've finish to configure everything but when i try to launch the bot i got this 
![image](https://github.com/shin202/ChatGPT-Discord-Bot/assets/45482611/a3e0cb84-d5bb-48fc-81dd-6bdfc741fac0)

**Comment by shin202** [comment]
Fixed. Please check this [Migration OpenAi from v3 to v4](https://github.com/shin202/ChatGPT-Discord-Bot/commit/79a755fcedfe5d5422f6e0bfc35f05c96acb4a0e)
