### ISSUE TITLE
Anyway to pay for extra support ?

### ISSUE THREAD

**Issue by MaelHan** [shin202/ChatGPT-Discord-Bot#71]
After migrating to V4 and the project working, not i got a problem with the OpenAI because i have to change the API by URL one.

It's your project and know you're code very well, is it possible to add you on Discord and paying for extra support ?

Thanks in advance, my Discord **yesiamkurt**

**Comment by shin202** [comment]
Thanks for your offer, but i'm quite busy right now. It's important to note that I've undertaken this project primarily as a means to further enrich and refine my skill set. And this is an open-source project, so you don't need to pay for it. If possible, you can contribute to this project by adding some new features.. I'm very appreciated. p/s: Sorry for my bad English 😁

**Comment by MaelHan** [comment]
No worry friend ! So i have one last question ! Do you know where i have to add an activity for the bot ?

I can't find the file path, thanks in advance !

**Comment by shin202** [comment]
> No worry friend ! So i have one last question ! Do you know where i have to add an activity for the bot ?
> 
> I can't find the file path, thanks in advance !

You can create your own slash command and chat command (aka prefix command) and put its in the same name folder.
